// The Worker's entry, wrapping what `opennextjs-cloudflare build` generates so
// the site can also answer a Cron Trigger (wrangler.jsonc `triggers.crons`).
// This is OpenNext's documented way to add a handler it does not provide.
//
// Once a day at 09:00 IST the cron asks the Next server, in-process, to send the
// pickup-day and return-day reminders (lib/reminders.ts). No request leaves the
// Worker; the key only proves the call came from here.

// @ts-ignore generated by `opennextjs-cloudflare build`, absent until then
import { default as handler } from "./.open-next/worker.js";
import { cronKey } from "./lib/cronKey";

export default {
  fetch: handler.fetch,

  async scheduled(_controller, env, ctx) {
    const secret = (env as { SESSION_SECRET?: string }).SESSION_SECRET;
    if (!secret) throw new Error("SESSION_SECRET is not set, so the reminders cannot be sent");
    const res: Response = await handler.fetch(
      new Request("https://cron.internal/api/cron/reminders", {
        method: "POST",
        headers: { authorization: `Bearer ${await cronKey(secret)}` },
      }),
      env,
      ctx
    );
    // Thrown so a failed run shows as failed in the dashboard's cron history.
    if (!res.ok) throw new Error(`reminders answered ${res.status}`);
  },
} satisfies ExportedHandler<CloudflareEnv>;
